name: proto_5gl
version: 1.0.0-dev
description: Loose prototype of a 5th-gen language with terse syntax.
homepage: https://github.com/thosakwe/5gl_proto
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: ">=1.8.0 <2.0.0"
dependencies:
  ace: ^0.7.2
  barback: ^0.15.2
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  string_editor: ^1.0.0-dev
dev_dependencies:
  test: ^0.12.15
transformers:
- dart_to_js_script_rewriter